import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
  },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, width: 80 },
  backText: { fontSize: 16, fontWeight: '500' },
  navTitle: { fontSize: 22, fontWeight: '600', letterSpacing: -0.5 },
  navSpacer: { width: 80 },
  keyboardAvoidingView: { flex: 1 },
  scrollView: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 40 },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
    marginTop: 8,
  },
  formGroup: { marginBottom: 16 },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  label: { fontSize: 14, fontWeight: '500' },
  errorInline: { fontSize: 12, fontWeight: '500' },
  input: {
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    borderWidth: 1,
  },
  countryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    marginBottom: 8,
  },
  countryButtonContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  countryFlag: { fontSize: 24 },
  countryButtonText: { fontSize: 15, fontWeight: '500' },
  helperText: { fontSize: 12, marginTop: 6 },
  textArea: { height: 120, paddingTop: 14 },
  charCount: { fontSize: 12, marginTop: 6, textAlign: 'right' },
  divider: { height: 1, marginVertical: 20 },
  actions: { gap: 12, marginTop: 8 },
  submitBtn: { height: 52, borderRadius: 6, justifyContent: 'center', alignItems: 'center' },
  submitBtnText: {
    fontSize: 15,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cancelBtn: { height: 52, borderRadius: 6, justifyContent: 'center', alignItems: 'center', borderWidth: 1 },
  cancelBtnText: {
    fontSize: 15,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: { width: '100%', maxWidth: 400, borderRadius: 12, maxHeight: '80%' },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  modalTitle: { fontSize: 18, fontWeight: '600' },
  countryList: { maxHeight: 500 },
  countryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
  },
  countryItemContent: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  countryInfo: { flex: 1 },
  countryName: { fontSize: 16, fontWeight: '500', marginBottom: 4 },
  countryDetails: { fontSize: 13 },
});
